name: deploy

on:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.2"
          gleam-version: "1.1"
          rebar-version: "3.23"

      - run: gleam format --check
        name: Format

      - run: gleam test
        name: Test

      - run: gleam run
        name: Build

      - uses: actions/upload-pages-artifact@v3
        name: Package
        with:
          path: ./output/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
